// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Afovg6jUn3abC5JUa9hX2iB0MwR_sBM',
    appId: '1:729103857773:web:a8dedad77bea30b6bba764',
    messagingSenderId: '729103857773',
    projectId: 'mobileapp-a31fb',
    authDomain: 'mobileapp-a31fb.firebaseapp.com',
    storageBucket: 'mobileapp-a31fb.appspot.com',
    measurementId: 'G-5F92F2LH5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAb7oPf4RI73PMPrMzUvwrG2TBGEkHhFA',
    appId: '1:729103857773:android:f10c5abf9ad32604bba764',
    messagingSenderId: '729103857773',
    projectId: 'mobileapp-a31fb',
    storageBucket: 'mobileapp-a31fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPu_GtDbEZpWblsbAyceWcGqBlfgrpwrA',
    appId: '1:729103857773:ios:e625518bbedc0effbba764',
    messagingSenderId: '729103857773',
    projectId: 'mobileapp-a31fb',
    storageBucket: 'mobileapp-a31fb.appspot.com',
    iosClientId: '729103857773-r7en2cjs8p6st5pghktsmppfh3va9ngo.apps.googleusercontent.com',
    iosBundleId: 'com.mobileapp.mobapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPu_GtDbEZpWblsbAyceWcGqBlfgrpwrA',
    appId: '1:729103857773:ios:e625518bbedc0effbba764',
    messagingSenderId: '729103857773',
    projectId: 'mobileapp-a31fb',
    storageBucket: 'mobileapp-a31fb.appspot.com',
    iosClientId: '729103857773-r7en2cjs8p6st5pghktsmppfh3va9ngo.apps.googleusercontent.com',
    iosBundleId: 'com.mobileapp.mobapps',
  );
}
